Fire Balls Power
Nintentando-Team-Software-Developmet/MarioBrosGame pull request #58
Opened 2024-07-01 19:07 UTC by GastonGutierrezC

## Description

## Related Issue(s)

## Changes Made

Performed the implementation of the movement and the fireball collisions with the different components of the map, now mario can kill the enemies with the fireball.

- [ ] add fireballs to Level1.json
- [ ] Add the necessary system and components for the fireballs.

## Screenshots (if applicable)

## Checklist

- [ ] Fireballs disappear if they leave the map. 
- [ ] Fireballs kill enemies.
- [ ] The fireballs bounce on the floor and blocks in the sky, but when they collide with the side of a block it explodes. 

Code reviuw 

@aguirrekarina 
@OropezaHugo

2024-07-01 19:46 UTC, OropezaHugo commented
The fireballs should not be able to collition with each other

2024-07-01 19:59 UTC, OropezaHugo commented
in random moments the fireballs disappear

2024-07-01 20:00 UTC, OropezaHugo commented
the max fireball number in the game at the same time must be 2

2024-07-01 20:01 UTC, OropezaHugo commented
when the fireball collides with mario after a time it kills him

2024-07-01 20:58 UTC, CatCoder36 reviewed
In general the code works but try to simplify and modularize the code, the functions should not have more than 30 lines at most or around, also try to simplify the logic or distribute it in more modules, for example the movement of a fireball if the logic becomes large put it to another system that only handles the movement and handling of appearance of the fireball that only handles the fireballSystem, remember that Aether2d gives us many functions to simplify the handling of movements and collisions, etc.

2024-07-01 20:58 UTC, CatCoder36 commented on MarioGame/Source/Components/DuctExtensionComponent.cs
> +public class DuctExtensionComponent: BaseComponent
Why is necesary a DuckExtensionComponet for this user history?

2024-07-01 20:58 UTC, CatCoder36 commented on MarioGame/Content/Levels/Level1.json
> +            "type": "FIREBALL",
fireballs as such are not entities of the level so they should not be in the level json, try to generate them based on an event or key when the level is running.

2024-07-01 20:58 UTC, CatCoder36 commented on MarioGame/Utils/Animations.cs
> +            { EntitiesName.FIREEXPROTION, fireExprotion}
Did you try to say explosion?

2024-07-01 20:58 UTC, CatCoder36 commented on MarioGame/Source/Systems/FireBoolSystem.cs
> +            if (otherEntityName == "GOOMBA" || otherEntityName == "KOOPA")
You can use the collision categories to simplify the logic of handling collisions with enemies, i.e. set up that fireball colliders can only collide with colliders of enemy type, review the property CollistionWith here:
https://nkast.github.io/Aether.Physics2D/Documentation/2.0/classnkast_1_1_aether_1_1_physics2_d_1_1_dynamics_1_1_fixture.html

2024-07-01 21:36 UTC, OropezaHugo commented
when I throw all the fireballs and none of them collide and go out of the camera view, I am not able to throw any fireball until I lose or win

2024-07-01 21:52 UTC, OropezaHugo submitted a review, later dismissed

2024-07-01 22:21 UTC, CatCoder36 requested changes

2024-07-01 22:21 UTC, CatCoder36 commented on MarioGame/Source/Systems/FireBoolSystem.cs
> +public class FireBoolSystem : BaseSystem
Please modularize this class better, the functions are too long.

2024-07-02 22:26 UTC, CatCoder36 approved these changes

2024-07-03 13:39 UTC, OropezaHugo approved these changes

2024-07-03 16:31 UTC, merged